- Dev Portfolio:
    - Github:
        - icon: si-github
          href: https://github.com/Kir4R00t
    - Website:
        - icon: https://cdn-icons-png.flaticon.com/512/5969/5969113.png
          href: https://kirahosting.fun
- Social:
    - Linkedin:
        - icon: si-linkedin
          href: https://www.linkedin.com/in/przemys%C5%82aw-sadowski-39266b297/
