---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - icon: si-github
          href: https://github.com/Kir4R00t

- Contact:
    - LinkedIn:
        - icon: si-linkedin
          href: https://www.linkedin.com/in/przemys%C5%82aw-sadowski-39266b297/
