- Portfolio:
    - My Website:
        icon: https://cdn-icons-png.flaticon.com/512/5969/5969113.png
        href: https://kirahosting.fun
        description: My personal website :)
        server: my-docker
        container: kirar00t-site

- Infrastructure:
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: https://npm.kirahosting.fun
        description: Reverse proxy and SSL
        server: my-docker
        container: reverseproxymanager-app-1

    - Portainer:
        icon: portainer.png
        href: https://portainer.kirahosting.fun/
        description: Docker management
        server: my-docker
        container: portainer

- Productivity:
    - Docmost:
        icon: docmost.png
        href: https://docmost.kirahosting.fun
        description: Notes and docs
        server: my-docker
        container: docmost-docmost-1
    - Mealie:
        icon: https://avatars.githubusercontent.com/u/92342333?s=48&v=4
        href: https://mealie.kirahosting.fun
        description: Recipe management app
        server: my-docker
        container: mealie

- Discord Bots:
    - FarmerBot:
        icon: discord.png
        href: https://github.com/Kir4R00t/FarmerBot
        description: Discord bot
        server: my-docker
        container: farmerbot-farmerbot-1

    - Discord Bot:
        icon: discord.png
        href: https://github.com/UnderscoreLodii/Discord-bot
        description: Discord bot
        server: my-docker
        container: discord-bot-app-1
        
- Utilities:
    - Calendar Scraper:
        icon: si-googlecalendar
        href: https://github.com/Kir4R00t/OutlookCalendarScraper
        description: Publishes shared calendar file
        server: my-docker
        container: outlookcalendarscraper-scraper
    - Homepage:
        icon: homepage.png
        href: https://gethomepage.dev/
        description: Dashboard
        server: my-docker
        container: homepage